const assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),logic=require('./docs/menu-logic');
const db=JSON.parse(fs.readFileSync('database/menu-database.json','utf8')),pub=JSON.parse(fs.readFileSync('docs/menus.json','utf8')),now=new Date('2026-09-11T12:00:00Z'),menu=pub.cafes.find(m=>m.cafeId==='cafe-006');
assert.deepEqual(pub.dataSource,{system:'airtable',baseName:'Hanoi Coffee Shuffle — Menu Operations',mode:'verified_snapshot'});
assert.equal(pub.cafes.length,50);assert.equal(menu.items.length,41);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-001').items.length,37);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-002').items.length,24);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-003').items.length,31);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-004').items.length,23);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-005').items.length,15);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-007').items.length,33);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-008').items.length,46);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-009').items.length,21);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-010').items.length,24);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-011').items.length,19);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-012').items.length,29);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-013').items.length,33);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-014').items.length,11);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-015').items.length,42);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-016').items.length,34);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-018').items.length,6);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-019').items.length,29);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-021').items.length,40);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-023').items.length,37);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-024').items.length,22);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-025').items.length,32);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-026').items.length,33);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-027').items.length,26);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-029').items.length,21);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-030').items.length,35);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-031').items.length,27);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-033').items.length,30);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-034').items.length,28);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-036').items.length,37);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-037').items.length,30);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-038').items.length,25);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-041').items.length,53);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-042').items.length,27);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-040').items.length,51);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-045').items.length,27);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-046').items.length,10);assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-050').items.length,46);assert.equal(pub.cafes.reduce((n,m)=>n+m.items.length,0),1222);assert(pub.cafes.every(m=>m.items.every(i=>i.status==='published'&&!('notes' in i))));assert.equal(pub.cafes.find(c=>c.cafeId==='cafe-044').items.length,26);
for(let n=0;n<50;n++){const item=logic.choose(menu,'coffee',null,true,180,now);assert.equal(item.type,'coffee');assert.equal(logic.highlight(item,180,now),'house_pick');assert.equal(item.priceVnd,75000);assert.equal(item.source.scope,'branch');}
const other=logic.choose(menu,'other',null,true,180,now);assert.equal(other.type,'other');assert.equal(logic.highlight(other,180,now),'house_pick');
assert.equal(logic.choose(db.cafes.find(c=>c.cafeId==='cafe-044'),'all',null,true,180,now),null);
const fixture=structuredClone(menu.items[3]);fixture.highlight='signature';fixture.highlightSource.label='Signature';assert.equal(logic.highlight(fixture,180,now),'signature');fixture.highlightSource.scope='brand';assert.equal(logic.highlight(fixture,180,now),'none');fixture.highlightSource.scope='branch';fixture.source.scope='brand';assert.equal(logic.eligible({items:[fixture]},'all',180,now).length,0);
fixture.source.scope='branch';fixture.source.url='javascript:alert(1)';assert.equal(logic.eligible({items:[fixture]},'all',180,now).length,0);fixture.source.url='https://example.com/menu';fixture.source.checkedAt='2026-09-12';assert.equal(logic.eligible({items:[fixture]},'all',180,now).length,0);fixture.source.checkedAt='2026-09-11';fixture.source.publishedAt='2025-01-01';assert.equal(logic.eligible({items:[fixture]},'all',180,now).length,0);fixture.source.publishedAt=null;fixture.availableUntil='2026-09-10';assert.equal(logic.eligible({items:[fixture]},'all',180,now).length,0);
const photo=structuredClone(menu.items[0]);photo.source={kind:'menu_photo',scope:'branch',evidenceId:'photo-20260917-test-menu',checkedAt:'2026-09-11',publishedAt:null};assert.equal(logic.eligible({items:[photo]},'all',180,now).length,1);photo.source.evidenceId='bad';assert.equal(logic.eligible({items:[photo]},'all',180,now).length,0);
assert.equal(logic.eligible(menu,'all',180,new Date('2027-04-01')).length,0);assert(!logic.validDate('2026-02-30'));assert(!logic.validDate(null));assert.equal(logic.choose({items:[]},'coffee',null,true,180,now),null);
const html=fs.readFileSync('database/menu-editor.html','utf8');assert(!html.includes('/*DATABASE*/'));for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);assert(!html.includes('localStorage'));assert(!html.includes('fetch('));
console.log('PASS: menu category and source rules, draft isolation, branch matching, distinct signature/house picks, stale/seasonal/future dates, price metadata and offline review editor syntax.');

const hermanos=pub.cafes.find(c=>c.cafeId==='cafe-048');assert.equal(hermanos.items.length,29);assert.equal(hermanos.items.find(i=>i.name.vi==='Espresso').priceVnd,40000);assert.equal(hermanos.items.find(i=>i.name.vi==='Matcha Latte').priceVnd,65000);assert(!hermanos.items.some(i=>/kem$|ice cream|herblend|oatside/i.test(i.name.vi)));
const briefly=pub.cafes.find(c=>c.cafeId==='cafe-047');assert.equal(briefly.items.length,32);assert.equal(briefly.items.filter(i=>i.highlight==='signature').length,8);assert.equal(new Set(briefly.items.map(i=>i.name.vi)).size,32);assert(briefly.items.filter(i=>i.highlight==='signature').every(i=>i.highlightSource?.label==='For You'));assert(!briefly.items.some(i=>/cake|pastr|croissant|baileys|macchiato/i.test(i.name.vi)));
