const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),logic=require('../docs/menu-logic');
const file=process.argv[2]?path.resolve(process.argv[2]):path.join(__dirname,'menu-database.json');
const db=JSON.parse(fs.readFileSync(file,'utf8')),cafes=JSON.parse(fs.readFileSync(path.join(root,'docs/cafes.json'),'utf8')).cafes;
const airtableConfig=JSON.parse(fs.readFileSync(path.join(__dirname,'airtable-sync-config.json'),'utf8'));
assert.equal(db.schemaVersion,1);assert.equal(db.reviewAfterDays,180);assert(logic.validDate(db.updatedAt));assert.equal(db.cafes.length,cafes.length);
const ids=new Set(),itemIds=new Set();for(const menu of db.cafes){assert(cafes.some(c=>c.id===menu.cafeId),'Unknown café');assert(!ids.has(menu.cafeId),'Duplicate café');ids.add(menu.cafeId);assert(['not_researched','needs_source','needs_branch_check','partial','complete'].includes(menu.coverage));assert(Array.isArray(menu.items));for(const item of menu.items){assert(typeof item.id==='string'&&item.id.length&&!itemIds.has(item.id),'Duplicate or empty item ID');itemIds.add(item.id);assert(item.name?.vi?.trim()&&item.name?.en?.trim(),'Both names required');assert(['coffee','other'].includes(item.type));assert(['draft','published','retired'].includes(item.status));assert(['none','signature','house_pick'].includes(item.highlight));assert(item.priceVnd===null||(Number.isInteger(item.priceVnd)&&item.priceVnd>0),'Invalid price');assert(item.priceNote&&typeof item.priceNote.vi==='string'&&typeof item.priceNote.en==='string');assert(!item.availableUntil||logic.validDate(item.availableUntil));if(item.status==='published'){assert(logic.trustedSource(item.source),'Published items require a branch-specific source');assert(logic.validDate(item.source.checkedAt));assert(!item.source.publishedAt||logic.validDate(item.source.publishedAt));assert(item.source.checkedAt<=db.updatedAt,'Future verification date');if(item.highlight!=='none'){assert(logic.trustedSource(item.highlightSource),'A highlight requires separate branch evidence');assert(logic.validDate(item.highlightSource.checkedAt));assert(item.highlightSource.label?.trim(),'Preserve the source highlight label');}}}}
const output={schemaVersion:1,updatedAt:db.updatedAt,reviewAfterDays:db.reviewAfterDays,dataSource:{system:'airtable',baseName:airtableConfig.baseName,mode:'verified_snapshot'},cafes:db.cafes.map(m=>({cafeId:m.cafeId,coverage:m.coverage==='complete'?'complete':'partial',items:m.items.filter(i=>i.status==='published').map(({notes,...item})=>item)}))};
fs.writeFileSync(path.join(root,'docs/menus.json'),JSON.stringify(output,null,2)+'\n');
console.log(`Menu data validated: ${cafes.length} branches, ${output.cafes.reduce((n,m)=>n+m.items.length,0)} published items; drafts excluded.`);
